### PR TITLE
prevent `get_backend` from overflowing the stack

### LINKED ISSUE #588: StackOverflowError on get_backend(::UnitRange)
MRE:

```
julia> using KernelAbstractions # v0.9.34

julia> get_backend(1:3)
ERROR: StackOverflowError:
Stacktrace:
 [1] get_backend(A::UnitRange{Int64}) (repeats 79984 times)
   @ KernelAbstractions C:\Users\konin_bt\.julia\packages\KernelAbstractions\sWSE0\src\KernelAbstractions.jl:519
```

I can imagine that trying to obtain the backend of an `UnitRange` is not an useful thing to do, but this probably still isn't desirable behavior.

This issue looks similar to https://github.com/JuliaGPU/KernelAbstractions.jl/issues/366.

### PR DESCRIPTION
**Pull request by nsajko**
Prevent the `get_backend` methods from overflowing the stack/recurring without bound.

Hoping this doesn't cause inference issues due to deeper call stacks.

Fixes #588

### CODE REVIEW

File: ext/LinearAlgebraExt.jl [hunk 1]
```diff
@@ -3,7 +3,7 @@ module LinearAlgebraExt
 using KernelAbstractions: KernelAbstractions
 using LinearAlgebra: Tridiagonal, Diagonal
 
-KernelAbstractions.get_backend(A::Diagonal) = KernelAbstractions.get_backend(A.diag)
-KernelAbstractions.get_backend(A::Tridiagonal) = KernelAbstractions.get_backend(A.d)
+KernelAbstractions.get_backend(A::Diagonal) = KernelAbstractions.get_backend_recur(x -> x.diag, A)
+KernelAbstractions.get_backend(A::Tridiagonal) = KernelAbstractions.get_backend_recur(x -> x.d, A)
```
Comment (nsajko) [inline ext/LinearAlgebraExt.jl:7]:
```suggestion
KernelAbstractions.get_backend(A::Diagonal) = KernelAbstractions.get_backend(A.diag)
KernelAbstractions.get_backend(A::Tridiagonal) = KernelAbstractions.get_backend(A.d)
```

File: src/KernelAbstractions.jl [hunk 2]
```diff
@@ -510,8 +510,23 @@ Get a [`Backend`](@ref) instance suitable for array `A`.
...
 
+function get_backend_recur(f::F, x) where {F}
+    t() = throw(ArgumentError("throwing to prevent a stack overflow, possibly a `get_backend` method is missing?"))
+    y = f(x)
+    if y isa typeof(x)
+        @noinline t()
+    end
+    return get_backend(y)
+end
+
```
Comment (nsajko) [inline src/KernelAbstractions.jl:521]:
```suggestion
```

**Review by vchuravy — APPROVED** [review]
Thanks!

I will backport this to the `0.9` branch
